import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { parseInputRecipe, parseOutputRecipe } from '../recipe-schema'
import type { InputRecipe } from '../recipe-schema'
import { fieldAt, validateBinding } from './recipe-binding.validator'

function fixture (name: string): unknown {
  const path = join(__dirname, '..', 'recipe-schema', 'fixtures', name)

  return JSON.parse(readFileSync(path, 'utf8'))
}

const output = parseOutputRecipe(fixture('product.output.json'))
const web = parseInputRecipe(fixture('shop-web.input.json'))
const api = parseInputRecipe(fixture('shop-api.input.json'))

function messages (input: InputRecipe): string[] {
  return validateBinding(input, output).map(issue => `${issue.path}: ${issue.message}`)
}

describe('validateBinding', () => {
  it('accepts the example recipes', () => {
    expect(messages(web)).toEqual([])
    expect(messages(api)).toEqual([])
  })

  it('reports a mapping to an unknown output field and an unknown source id', () => {
    const bad: InputRecipe = { ...api, mapping: { ...api.mapping, colour: { from: 'item.colour' }, title: { from: 'nothing' } } }
    expect(messages(bad)).toEqual(expect.arrayContaining([
      'mapping.colour: output "product" has no field "colour"',
      'mapping.title.from: "nothing" does not start with a known id',
    ]))
  })

  it('reports a required field that is never mapped', () => {
    const { title: _title, ...rest } = api.mapping
    expect(messages({ ...api, mapping: rest })).toContain('mapping: required output field "title" is not mapped')
  })

  it('rejects mapping a generated field and a wrong each target', () => {
    const bad: InputRecipe = { ...api, mapping: { ...api.mapping, scrapedAt: { from: 'item.at' }, images: { each: 'item.images', fields: {} } } }
    expect(messages(bad)).toEqual(expect.arrayContaining([
      'mapping.scrapedAt: "scrapedAt" is generated by the engine and cannot be mapped',
      'mapping.images: an "each" rule needs an output field of type array whose items are objects',
    ]))
  })

  it('rejects browser steps in api mode outside the bootstrap, and api steps in web mode', () => {
    const badApi: InputRecipe = { ...api, steps: [{ type: 'goto', url: 'x' }, ...api.steps] }
    expect(messages(badApi)[0]).toMatch(/steps\.0: "goto" needs a browser/)
    const badWeb: InputRecipe = { ...web, steps: [{ type: 'request', url: 'x', id: 'r' }, ...web.steps] }
    expect(messages(badWeb)[0]).toMatch(/steps\.0: "request" is an api step/)
  })

  it('rejects next.selector in api mode and next.jsonpath in web mode', () => {
    const badApi: InputRecipe = { ...api, steps: [{ type: 'paginate', next: { selector: 'a' }, steps: api.steps[0].type === 'paginate' ? api.steps[0].steps : [] }] }
    expect(messages(badApi)).toContain('steps.0.next: next.selector needs a browser; use next.url or next.jsonpath in api mode')
  })

  it('rejects two emitting constructs on one path and duplicate ids', () => {
    const bad: InputRecipe = {
      ...web,
      steps: [
        { type: 'extract', id: 'links', selector: 'a', kind: 'css', many: true },
        { type: 'extract', id: 'links', selector: 'b', kind: 'css' },
        { type: 'forEach', over: 'links', as: 'link', emit: true, steps: [{ type: 'emit' }] },
      ],
    }
    expect(messages(bad)).toEqual(expect.arrayContaining([
      'steps.1: id "links" is already bound on this path',
      'steps.2.steps.0: inside an emitting forEach; only one emit per path',
    ]))
  })

  it('knows paginate "as" bindings and forEach variables', () => {
    const ok: InputRecipe = {
      ...api,
      steps: [{
        type:  'paginate',
        next:  { jsonpath: '$.cursor', as: 'cursor' },
        steps: [
          { type: 'request', id: 'list', url: '{{start.url}}?cursor={{cursor}}', as: 'json' },
          { type: 'extract', id: 'items', from: 'list', selector: '$.items[*]', kind: 'jsonpath', many: true },
          { type: 'forEach', over: 'items', as: 'item', emit: true, steps: [] },
        ],
      }],
    }
    expect(messages(ok)).toEqual([])
  })
})

describe('fieldAt', () => {
  it('walks into object fields by dotted path', () => {
    expect(fieldAt(output.fields, 'seller.name')?.type).toBe('string')
    expect(fieldAt(output.fields, 'seller.phone')).toBeUndefined()
    expect(fieldAt(output.fields, 'title.x')).toBeUndefined()
  })
})
