import { API_ONLY_STEPS, WEB_ONLY_STEPS } from '../recipe-schema'
import type { FieldSpec, InputRecipe, MappingRule, OutputRecipe, Step } from '../recipe-schema'
import type { BindingIssue } from './recipe-binding.error'

const RESERVED = new Set(['page', 'start', 'vars'])
const WEB_ONLY = new Set<string>(WEB_ONLY_STEPS)
const API_ONLY = new Set<string>(API_ONLY_STEPS)

/**
 * Checks that an input recipe can actually feed its output recipe:
 *
 * - every mapping key names an output field (dotted for nested objects), and an
 *   `each` rule targets an array of objects;
 * - every `from` / `each` / `over` root is a step id bound anywhere in the
 *   recipe, a `forEach` variable, a `paginate` `as` binding, or one of `page`,
 *   `start`, `vars` (`emit` snapshots the whole scope chain, so any id can feed
 *   the mapping);
 * - every required output field is mapped, defaulted, or generated;
 * - step ids are unique along any path;
 * - web-only steps appear only in web recipes or inside a bootstrap, api-only
 *   steps only in api recipes, and `next.selector` only in web mode;
 * - exactly one emitting construct exists on any path (the two branches of an
 *   `if` are separate paths).
 *
 * @param input - A parsed input recipe.
 * @param output - The parsed output recipe it names.
 * @returns Every problem found; empty when the recipes bind.
 */
export function validateBinding (input: InputRecipe, output: OutputRecipe): BindingIssue[] {
  const issues: BindingIssue[] = []
  const report = (path: string, message: string): void => { issues.push({ recipeId: input.id, path, message }) }

  const known = new Set<string>(RESERVED)
  const varNames = [input.vars ?? {}, ...input.start.map(point => point.vars ?? {})].flatMap(record => Object.keys(record))
  for (const name of varNames) known.add(name)

  walkSteps(input.steps, 'steps', input.mode, known, report, { emitting: false, ids: new Set() })
  if (input.session?.bootstrap !== undefined) {
    walkSteps(input.session.bootstrap.steps, 'session.bootstrap.steps', 'web', new Set(RESERVED), report, { emitting: false, ids: new Set(), bootstrap: true })
  }

  for (const [target, rule] of Object.entries(input.mapping)) {
    const field = fieldAt(output.fields, target)
    if (field === undefined) {
      report(`mapping.${target}`, `output "${output.id}" has no field "${target}"`)
    } else if (field.generated !== undefined) {
      report(`mapping.${target}`, `"${target}" is generated by the engine and cannot be mapped`)
    } else if ('each' in rule && (field.type !== 'array' || field.items?.type !== 'object')) {
      report(`mapping.${target}`, 'an "each" rule needs an output field of type array whose items are objects')
    }
    checkRuleSources(rule, `mapping.${target}`, known, report)
  }

  for (const [name, field] of Object.entries(output.fields)) {
    if (field.required !== true || field.generated !== undefined || field.default !== undefined) continue
    const mapped = Object.keys(input.mapping).some(target => target === name || target.startsWith(`${name}.`))
    if (!mapped) report('mapping', `required output field "${name}" is not mapped`)
  }

  return issues
}

interface WalkState {
  emitting:   boolean
  ids:        Set<string>
  bootstrap?: boolean
}

function walkSteps (steps: readonly Step[], path: string, mode: 'web' | 'api', known: Set<string>, report: (path: string, message: string) => void, state: WalkState): void {
  for (const [index, step] of steps.entries()) walkStep(step, `${path}.${index}`, mode, known, report, state)
}

function walkStep (step: Step, at: string, mode: 'web' | 'api', known: Set<string>, report: (path: string, message: string) => void, state: WalkState): void {
  if (mode === 'api' && WEB_ONLY.has(step.type)) report(at, `"${step.type}" needs a browser; this recipe runs in api mode (use session.bootstrap for browser steps)`)
  if (mode === 'web' && API_ONLY.has(step.type)) report(at, `"${step.type}" is an api step; this recipe runs in web mode`)
  if (state.bootstrap === true && (step.type === 'emit' || (step.type === 'forEach' && step.emit !== undefined))) report(at, 'a bootstrap produces a session, not records')
  if (step.id !== undefined) {
    if (state.ids.has(step.id) || RESERVED.has(step.id)) report(at, `id "${step.id}" is already bound on this path`)
    state.ids.add(step.id)
    known.add(step.id)
  }
  if (step.type === 'extract' && step.from !== undefined && !known.has(step.from)) report(`${at}.from`, `"${step.from}" is not a known id`)
  if (mode === 'web' && state.bootstrap !== true && step.type === 'extract' && step.kind === 'table' && step.from === undefined) {
    const foreign = (['sheet', 'slide', 'shapes', 'align', 'includeHidden'] as const).filter(option => step[option] !== undefined)
    if (foreign.length > 0) report(at, `a "table" extract on a web page reads its HTML tables; ${foreign.map(option => `"${option}"`).join(', ')} belong to PDFs, workbooks or decks (fetch one with a request step in an api recipe)`)
  }
  if (step.type === 'collect' && !known.has(step.into)) report(`${at}.into`, `"${step.into}" is not a known id: set it to [] before the loop that collects into it`)
  const nested = (): WalkState => ({ ...state, ids: new Set(state.ids) })
  switch (step.type) {
    case 'forEach': {
      if (step.over !== undefined && !known.has(step.over)) report(`${at}.over`, `"${step.over}" is not a known id`)
      if (mode === 'api' && step.selector !== undefined) report(`${at}.selector`, 'forEach over selector iterates live elements and needs a browser; use over (a list id) in api mode')
      const emits = step.emit !== undefined
      if (emits && state.emitting) report(at, 'nested inside another emitting construct; only one emit per path')
      const inner = { ...nested(), emitting: state.emitting || emits }
      known.add(step.as)
      inner.ids.add(step.as)

      return walkSteps(step.steps, `${at}.steps`, mode, known, report, inner)
    }
    case 'if': {
      // The branches are exclusive: each sees the ids bound before the `if`, neither sees the other's.
      walkSteps(step.steps, `${at}.steps`, mode, known, report, nested())

      return walkSteps(step.else ?? [], `${at}.else`, mode, known, report, nested())
    }
    case 'paginate': {
      if (mode === 'api' && 'selector' in step.next) report(`${at}.next`, 'next.selector needs a browser; use next.url or next.jsonpath in api mode')
      if (mode === 'web' && 'jsonpath' in step.next) report(`${at}.next`, 'next.jsonpath reads an api document; use next.selector or next.url in web mode')
      if ('jsonpath' in step.next && step.next.as !== undefined) known.add(step.next.as)

      return walkSteps(step.steps, `${at}.steps`, mode, known, report, nested())
    }
    case 'emit': {
      if (state.emitting) report(at, 'inside an emitting forEach; only one emit per path')

      return
    }
    default: { return
    }
  }
}

function checkRuleSources (rule: MappingRule, path: string, known: Set<string>, report: (path: string, message: string) => void, relative = false): void {
  if ('from' in rule) {
    const sources = Array.isArray(rule.from) ? rule.from : [rule.from]
    for (const source of sources) {
      if (relative) continue
      const root = rootOf(source)
      if (!known.has(root)) report(`${path}.from`, `"${source}" does not start with a known id`)
    }
  } else {
    if (!relative && !known.has(rootOf(rule.each))) report(`${path}.each`, `"${rule.each}" does not start with a known id`)
    for (const [name, nested] of Object.entries(rule.fields)) checkRuleSources(nested, `${path}.fields.${name}`, known, report, true)
  }
}

function rootOf (source: string): string {
  return source.replaceAll(/\[(\d+)\]/g, '.$1').split('.', 1)[0]
}

/**
 * The output field at a dotted target, walking into `object` members.
 *
 * @param fields - The output recipe's fields.
 * @param target - A mapping key.
 * @returns The field, or `undefined`.
 */
export function fieldAt (fields: Record<string, FieldSpec>, target: string): FieldSpec | undefined {
  const segments = target.split('.')
  let current: FieldSpec | undefined = fields[segments[0]]
  for (const segment of segments.slice(1)) {
    if (current?.type !== 'object') return undefined
    current = current.fields?.[segment]
  }

  return current
}
